apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: andreas-kavountzis-pipeline-from-scratch
commonAnnotations:
  enzo: "true"
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: andreas-kavountzis-pipeline-from-scratch
    newName: andreask/andreas-kavountzis-pipeline-from-scratch
    newTag: "v0.1.0"
patches:
  - path: host_patch.json
    target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: react-intro
